# Generated by Django 6.0.3 on 2026-04-17 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka samochodu:')),
                ('model', models.CharField(max_length=100, verbose_name='Model samochodu')),
                ('year', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Rok produkcji')),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=10, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(9999999)], verbose_name='Cena')),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Przebieg (w km)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
