# Generated by Django 6.0.5 on 2026-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Opis,'),
        ),
    ]
